version: '2'
services:
  github_retriever_service:
    build: ./github_retriever_docker
    image: github_retriever_app
    environment:
      - token=${TOKEN}
      - repo=${GITHUB_REPO}
    volumes:
      - ./csv_data:/usr/src/app/csv_data
  jira_retriever_service:
    build: ./jira_retriever_docker
    image: jira_retriever_app
    volumes:
      - ./csv_data:/usr/src/app/csv_data
    environment:
      - project=${JIRA_PROJECT}
      - server=${JIRA_SERVER}
  graphics_generator_service:
    build: ./graphics_generator_docker
    image: graphics_generator_app
    volumes:
      - ./csv_data:/usr/src/app/csv_data
