version: '2'
services:
  github_retriever_docker:
    build: ./github_retriever_docker
    image: github_retriever_app
    environment:
      - token=${TOKEN}
    volumes:
      - ./csv_data:/usr/src/app/csv_data
  jira_retriever_docker:
    build: ./jira_retriever_docker
    image: jira_retriever_app
    volumes:
      - ./csv_data:/usr/src/app/csv_data
